### ISSUE TITLE
Fraudulent claims made; i.e. No neural network code found in repository despite claims of neural network use

### ISSUE THREAD

**Issue by JordanMicahBennett** [AaronLS/CellularAutomataAsNeuralNetwork#2]
The author of the  "CellularAutomataAsNeuralNetwork" claims to have used neural networks to write the automata, but there are no neural networks.

There are variables called  "weights" or "activation" that relate to the topic of neural networks, but these variables don't seem to be involved in an actual neural network calculations.

**_Calling some variables by names of items related to a process, doesn't mean those variables are actually involved in said process_**!

**Comment by AaronLS** [comment]
The code for the NN is located here:
https://github.com/AaronLS/CellularAutomataAsNeuralNetwork/tree/master/CellLifeGame1/Model
